# Generated by Django 4.2 on 2025-04-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='unitePrice',
            new_name='unitPrice',
        ),
    ]
