# Generated by Django 4.2 on 2025-04-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0002_rename_uniteprice_track_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
