# Generated by Django 4.2 on 2025-04-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0003_alter_track_composer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
    ]
